"""empty message

Revision ID: b3c98d8c15e5
Revises: 6f541788cc73
Create Date: 2023-02-21 23:26:50.840152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c98d8c15e5'
down_revision = '6f541788cc73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('altura', sa.String(length=250), nullable=False),
    sa.Column('genero', sa.String(length=250), nullable=False),
    sa.Column('peso', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('personajes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('altura', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('genero', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('peso', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='personajes_pkey')
    )
    op.drop_table('personaje')
    # ### end Alembic commands ###
